---
# mcMMO database file

# The type of database to use.
# Supported types: json, yaml, igbinary
# NOTE: If you are using igbinary, you may need to install php-igbinary manually.
type: yaml

# Configuration for YAML
YAML:
  datafolder: profiles

# Configuration for JSON
JSON:
  datafolder: profiles

# Configuration for igbinary
IGBINARY:
  datafolder: profiles
...